name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create ZIP package
        run: zip -r deploy_package.zip application.py requirements.txt

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          region: ${{ secrets.AWS_REGION }}
          application_name: cmtr-ngt8zi57-app
          environment_name: cmtr-ngt8zi57-env
          version_label: "v-${{ github.run_number }}"
          deployment_package: deploy_package.zip
